export const ADD_DAILY_WATER = 'ADD_DAILY_WATER';
export const RESET_DAILY_WATER = 'RESET_DAILY_WATER';
export const INITIALIZE_DAILY_WATER = 'INITIALIZE_DAILY_WATER';

export const SET_TODAYS_DATE = 'SET_TODAYS_DATE';
